Added enable/disable for each comparison method

diff --git a/diffuzzy b/diffuzzy
--- a/diffuzzy
+++ b/diffuzzy
@@ -14,23 +14,28 @@ function diffuzzy_compare
 	local PATH2="$2"
 	local STATUS=0
 
-	#echo "Comparing:"
-	#for P in "$@"; do
-	#	echo "  $P"
-	#done
-
-	diffuzzy_compare_existential "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if [ $VERBOSE -ge 1 ]; then
+		echo "Comparing:"
+		for P in "$@"; do
+			echo "  $P"
+		done
 	fi
 
-	diffuzzy_compare_type "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if $COMPARE_EXISTENTIAL; then
+		diffuzzy_compare_existential "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
-	local PATH_TYPE=$(stat -c %F "$1")
-	case "$PATH_TYPE" in
+	if $COMPARE_TYPE; then
+		diffuzzy_compare_type "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
+	fi
+
+	case $(stat -c %F "$1") in
 		"directory")
 			diffuzzy_compare_directories "$@"
 			return $?
@@ -42,9 +47,11 @@ function diffuzzy_compare
 			;;
 	esac
 
-	diffuzzy_compare_size "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if $COMPARE_SIZE; then
+		diffuzzy_compare_size "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
 	# full comparison if both files are small
@@ -53,19 +60,25 @@ function diffuzzy_compare
 		return $?
 	fi
 
-	diffuzzy_compare_header "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if $COMPARE_HEADER; then
+		diffuzzy_compare_header "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
-	diffuzzy_compare_footer "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if $COMPARE_FOOTER; then
+		diffuzzy_compare_footer "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
-	diffuzzy_compare_offsets "$@"
-	if [ $? -ne 0 ]; then
-		return 1
+	if $COMPARE_OFFSETS; then
+		diffuzzy_compare_offsets "$@"
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
 	return $STATUS
@@ -96,7 +109,6 @@ function diffuzzy_compare_directories
 				SUBPATHS+=("$P/$FILE")
 			done
 
-			#echo "$FILE"
 			diffuzzy_compare "${SUBPATHS[@]}"
 			if [ $? -ne 0 ]; then
 				STATUS=1
@@ -239,7 +251,7 @@ function diffuzzy_compare_type
 	return $STATUS
 }
 
-# \brief Displays the help and exits the program
+# \brief Output the help documentation then exit
 function diffuzzy_help
 {
 	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
@@ -251,9 +263,21 @@ function diffuzzy_help
 	echo
 	echo "Options:"
 	echo "  -h, --help"
-	echo "    Display this help message and exit."
+	echo "    Output this help message and exit."
+	echo "  -m,--method method1,method2,..."
+	echo "    A comma-separated list of which comparisons to run:"
+	echo "      existential  default  Detect missing objects"
+	echo "      type         default  Detect mismatched file types"
+	#echo "      symlink      default  Detect symlinks with different targets"
+	#echo "      device       default  Detect major and minor type mismatches"
+	echo "      size         default  Detect file size mismatches"
+	echo "      header       default  Compare the first 512 bytes"
+	echo "      footer       default  Compare the last 512 bytes"
+	echo "      offsets      default  Compare floor(log(2,size)) random 512 byte offsets"
 	echo "  --unittest"
 	echo "    Perform unit tests to verify functionality of this script."
+	echo "  -v"
+	echo "    Output each set of files that are compared."
 	echo
 	echo "Version:"
 	echo "  $NAME $VERSION"
@@ -484,6 +508,18 @@ function diffuzzy_unittest
 }
 
 #------------------------------------------------------------------------------
+# default configuration
+
+COMPARE_EXISTENTIAL=false
+COMPARE_TYPE=false
+COMPARE_SIZE=false
+COMPARE_HEADER=false
+COMPARE_FOOTER=false
+COMPARE_OFFSETS=false
+METHOD=existential,type,size,header,footer,offsets
+VERBOSE=0
+
+#------------------------------------------------------------------------------
 # command line arguments
 
 THIS="$0"
@@ -508,6 +544,24 @@ if [ $# -eq 1 ]; then
 			;;
 	esac
 fi
+if [ "$1" = "-v" ]; then
+	VERBOSE=1
+	shift
+fi
+if [ "$1" = "-m" -o "$1" = "--method" ]; then
+	METHOD="$2"
+	shift 2
+fi
+for M in $(echo -n "$METHOD" | tr ',' ' '); do
+	case "$M" in
+		"existential") COMPARE_EXISTENTIAL=true ;;
+		"type") COMPARE_TYPE=true ;;
+		"size") COMPARE_SIZE=true ;;
+		"header") COMPARE_HEADER=true ;;
+		"footer") COMPARE_FOOTER=true ;;
+		"offsets") COMPARE_OFFSETS=true ;;
+	esac
+done
 
 #------------------------------------------------------------------------------
 # begin execution
